name: whoop-collector
on:
  push:
    branches:
      - 'main'
    paths:
      - 'collector/whoop/**'
jobs:
  build-and-push-whoop:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v3
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Login to DigitalOcean Container Registry
        uses: docker/login-action@v2
        with:
          registry: registry.digitalocean.com
          username: ${{ secrets.DIGITALOCEAN_TOKEN }}
          password: ${{ secrets.DIGITALOCEAN_TOKEN }}
      - name: Build and push whoop collector
        uses: docker/build-push-action@v3
        with:
          context: "{{defaultContext}}:collector/whoop"
          push: true
          tags: registry.digitalocean.com/pokedesk-cr/whoop-collector:latest
